### PR TITLE
Use correct type for !== comparison

### PR DESCRIPTION
**Pull request by ianp**
Sorry it's taken me so long to get around to this!

### CODE REVIEW

**Comment by manast** [comment]
tests are broken though with errors like ```(node:4734) UnhandledPromiseRejectionWarning: Error: File /home/travis/build/OptimalBits/bull/test/fixtures/fixture_processor_slow.js.js does not exist
```

**Comment by ianp** [comment]
Ha! Yes, turns out they were only passing before because the comparison failing was hiding the fact. that the list of supported extensions was incorrect. My bad for not checking.

I've also replaced the `indexOf !== -1` test with `includes` which was added in Node 6, which is the minimum supported version according to the package file, and reads better IMHO.

**Comment by ianp** [comment]
As far as I can see the CI tests are failing because of a module version incompatibility, unrelated to this PR. The version of `get-stdin` (added 10 days ago) looks like it needs Node 8. Not sure if you want to make 8 the minimum supported version of do something about that dependency?

**Comment by manast** [comment]
@ianp yes I think I will remove nodejs 6 support for the next version because it is quite old by now anyway. Thanks for the fix.

**Pull request merged**
