### PR TITLE
feat: support job.discard function in sandboxed processors

### PR DESCRIPTION
**Pull request by alolis**
* Implement Job.prototype.isDiscarded

### CODE REVIEW

**Comment by manast** [comment]
I am going to merge this because I understand this feature is useful to you despite I am not very happy with the "discard" functionality to begin with since it is a bit hackish in the sense that it is just a local property of the job and not persisted which can lead to surprising behaviours.

**Comment by alolis** [comment]
@manast, thanks for the speedy handling of the PR! 

I understand your concern. It did cross my mind as well but then I thought that the people who use this library are engineers and they should know better to not mess with things they do not fully understand yet :) 

My intentions for this PR will be more clear as soon as I reply to the comments [here](https://github.com/OptimalBits/bull/issues/1098#issuecomment-776918687) and [here](https://github.com/OptimalBits/bull/issues/1113#issuecomment-851642543).

If you do feel that this PR needs to be reverted however in case you've changed your mind, feel free to do so of course!

**Comment by alolis** [comment]
@manast, [this](https://www.alexanderlolis.com/riding-the-bull), explains why I needed the function.

I hope you approve this article. There are a few people in issues that have been asking me about my approach so I thought to just write up everything.

**Comment by manast** [comment]
@alolis that was a very informative article, always helpful to understand what pain points are there for bull users so that I can try to mitigate them with new features.

**Comment by alolis** [comment]
Cheers @manast! I am glad you liked it

**Pull request merged**
