### PR TITLE
Improved docs for guide

### PR DESCRIPTION
**Pull request by j05u3**
I lost some time finding out why the async/await example wasn't working in my setup (the job was getting stalled because I was never calling the done function).

### CODE REVIEW

**Comment by ritter** [comment]
@j05u3 I believe if you don't specify a 2nd parameter to the process function, bull expects it to be a promise and you should just return a promise.  No need to define and call done.

**Comment by j05u3** [comment]
> @j05u3 I believe if you don't specify a 2nd parameter to the process function, bull expects it to be a promise and you should just return a promise. No need to define and call done.

It is true, but in the example there was a second parameter and it is not clear that it is a function you should call (the done function) and its name is misleading :) 

`myFirstQueue.process(async (job, data) => {
  return doSomething(data);
});`

**Comment by ritter** [comment]
> `myFirstQueue.process(async (job, data) => { return doSomething(data); });`

I don't think `data` is correct as the 2nd parameter and should be:
`myFirstQueue.process(async (job) => { return doSomething(job.data); });`
Where `doSomething()` returns a promise.

**Comment by manast** [comment]
Thanks for the improvement in the docs. I will try to improve it even a bit more.

**Pull request closed without merging**
