### PR TITLE
Performance fixes

### PR DESCRIPTION
**Pull request by manast**
This PR includes various performance fixes. Some related to faster javascript, but the most important one is the one related to notifying waiting jobs, which now uses a blocking operation instead of pubsub. This solution completely removes the overhead of having many concurrent workers reacting to the pubsub 'added' event.

### CODE REVIEW

**Comment by manast** [comment]
@bradvogel the optimization is ready. Having many concurrent workers now should not affect the queue's performance as badly as it did before.

**Comment by bradvogel** [comment]
Awesome! We're going to rerun the new benchmarks and post an update in https://github.com/bee-queue/bee-queue/issues/67

**Comment by manast** [comment]
Also fixes #638

**Comment by manast** [comment]
Issue #637 cannot be reproduced in this branch either.

**Pull request merged**
