### PR TITLE
Remove extra file in repo

### PR DESCRIPTION
**Pull request by doublerebel**
Hello,

I am poking around in bull internals (I'm writing a new frontend with full test coverage) and I find this extra file.  It looks like it's not a dependency for any other code, perhaps it snuck in with the commit by accident?

Best,
doublerebel

### CODE REVIEW

**Comment by manast** [comment]
This is actually a prototype for a distributed state machine built on top of bull.

**Comment by tinybug** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by fearphage** [comment]
> This is actually a prototype for a distributed state machine built on top of bull.

That sounds like something for the `samples`/`examples` folder and not `lib` personally. I just saw the [cluster-queue file](https://github.com/OptimalBits/bull/blob/3cdd32bc4e9847e9d480fe54015991d9c10aaa1a/lib/cluster-queue.js) and thought the exact same thing.

`lib` should contain required resources for the library in general. It's weird that you include these samples when downloaded from npm also. What purpose to they serve to an end user of this library? https://docs.npmjs.com/files/package.json#files

**Comment by fearphage** [comment]
It [looks like](https://github.com/OptimalBits/bull/blob/52563935d983fe4226c6fc31cc929c9537c25c4b/lib/queue.js#L9-L11) `lib` should contain only 4 files:

* queue (main)
* jobs 
* scripts
* time-manager

**Comment by bradvogel** [comment]
Removed these scripts in https://github.com/OptimalBits/bull/pull/515/files. This can be closed.

**Pull request closed without merging**
