### PR TITLE
Try to fix Promise related memory leaks

### PR DESCRIPTION
**Pull request by leolannenmaki**
I ran into similar issues as described here https://github.com/OptimalBits/bull/issues/144 and here https://github.com/OptimalBits/bull/issues/243. The issue descriptions and the comment here https://github.com/OptimalBits/bull/issues/243#issuecomment-182936122 helped me to maybe fix the at least some of the leaks. I used node-inspector and snapshotting to debug this.

To test this I had a node program running bull, but doing absolutely nothing. Without these changes the memory consumption would steadily just grow. Now it seems more or less stable.

I also tried to avoid rebinding functions and creating closures in `processJobs` etc.

### CODE REVIEW

**Comment by leolannenmaki** [comment]
Tests pass locally on Node 4, Travis says no on Node 0.10 https://travis-ci.org/OptimalBits/bull/builds/109556222

**Comment by jbourassa** [comment]
Well done. I was just about to create a PR for this.

For what it's worth, the `finally` recursion leak is "by design", see petkaantonov/bluebird#1009

**Comment by wearhere** [comment]
@manast d58a2bb and ae32056 fix the memory leak @bradvogel and I mentioned, a hearty +1 to this PR! Thanks @leolannenmaki and @jbourassa!

**Comment by manast** [comment]
Than you for this great PR. I will make a release as soon as possible.

**Pull request merged**
