### PR TITLE
Duration change

### PR DESCRIPTION
**Pull request by mikewash**

### CODE REVIEW

**Comment by mikewash** [comment]
Changed stalled times

**Comment by bradvogel** [comment]
What is this?

**Comment by mikewash** [comment]
I’m not sure what you are specifically asking, but this is a fork of bull I’m using to fix an issue I’m currently having on production with revolving jobs between wait and active lists for version 2.2.6.

**Comment by bradvogel** [comment]
But this is a pr into the master branch. I think you meant to pr into another branch.

**Comment by mikewash** [comment]
Sorry about that, I forked the code last night and must thought I was within my own fork you can delete this.

**Pull request closed without merging**
