### PR TITLE
fix(clean-priority): remove job from priority set on clean

### PR DESCRIPTION
**Pull request by bdentino**
First contribution, so apologies if I've missed anything or stepped on any project standards - happy to make updates to the PR as necessary.

I noticed some strange behavior in one of my applications where jobs were not being processed according to priority. I could reproduce reliably in production, but not in a new staging environment so I dug into the repo and checked some of the keys in Redis. Long story short, I found out that whenever I run the `cleanJobsInSet` script on the waiting jobs it causes the priority set to go wildly out of sync with the jobs list because these jobs aren't being removed, and I believe this was causing new jobs to get inserted into the jobs list at strange indexes. I have a script running in production that periodically cleans up the different states, and once I re-synced by resetting the priority key and removing all jobs the problem was gone. 

This fix simply updates the `cleanJobsInSet` script to remove each job from the priority set if present. 

I don't know when the clean feature was introduced, but I wonder if this could have been causing the OPs issues in #733?

### CODE REVIEW

**Comment by manast** [comment]
thanks for the patch, It looks great. However I think you may have also added the ```addMany```  feature in the same PR, it is better to keep them as 2 different.

**Comment by bdentino** [comment]
You are absolutely correct - my mistake! I've removed those commits from this branch. 

On that note, would you consider accepting a PR for the `addMany` feature? I have some scripts that schedule 100k+ jobs and it has significantly improved the performance of those scripts, but it doesn't seem to be an issue any other users are running into.

**Comment by luastoned** [comment]
I encountered the same bug, when will this fix be released?

**Comment by bdentino** [comment]
ping @manast - any interest in merging this still?

**Comment by manast** [comment]
@bdentino looks good, very sorry that I missed the reply to my comment :/

**Pull request merged**
