### PR TITLE
Ability to process all named jobs from one process function

### PR DESCRIPTION
**Pull request by ariksfaradi**
https://github.com/OptimalBits/bull/issues/823

### CODE REVIEW

**Comment by manast** [comment]
nice addition, thanks!.

**Comment by ritter** [comment]
Would be great to get this into the documentation as well.

**Comment by ariksfaradi** [comment]
thanks for the responses, I added documentation suggestion as well

**Comment by hoo29** [comment]
https://github.com/OptimalBits/bull/pull/898 I opened a few days ago achieves the same goal in a different way. If this one gets merged I'll close my one.

**Comment by hoo29** [comment]
@manast are you able to merge this request?

**Pull request merged**
