### PR TITLE
WIP: Replace bluebird function usages with native Promise

### LINKED ISSUE #1027: TypeError: scripts.updateDelaySet(...).then(...).catch(...).
## Description
I am trying re-use Redis session following PATTERNS.md. All is working until the "New Queue" code, but when I try call ".process" queue method i exception appears

**_TypeError: scripts.updateDelaySet(...).then(...).catch(...).return is not a function
services_monitor.1.wfdxm3rsmh11@l01752papp0    |     at delayUpdate (/var/www/html/node/node_modules/bull/lib/queue.js:867:16)_**

## Minimal, Working Test code to reproduce the issue.
The code:
`var Queue = require('bull');

var Redis = require('ioredis')
var client = new Redis(6379, 'redis');
var subscriber = new Redis(6379, 'redis');

var opts = {
  createClient: function (type) {
    switch (type) {
      case 'client':
        return client;
      case 'subscriber':
        return subscriber;
      default:
        return new Redis();
    }
  }
}`

var queueMonitor = new Queue('monitor', opts); //-> returns the Queue object  
queueMonitor.process(function(job, done){  // the error appears here
  console.log("Received message", job.data.msg);
  done();
});

## Bull version
bull 3.4.7
ioredis 4.0.0

### PR DESCRIPTION
**Pull request by pc-jedi**
- [x] `.return` is a short hand by Bluebird. [Bluebird .return](http://bluebirdjs.com/docs/api/return.html)
If the ioredis client is created by the user without using Bluebird Promises the `.return` function is not available.
- [x] `.spread` is Bluebird implementation for destructuring an array of promises. [Bluebird .spread](http://bluebirdjs.com/docs/api/spread.html)
It can be replaced by ES6 destructuring.
- [x] `.timeout` [Bluebird .timeout](http://bluebirdjs.com/docs/api/timeout.html)
- [x] `.map` [Bluebird .map](http://bluebirdjs.com/docs/api/map.html)
- [x] `Promise.map` replaced by `Promise.resolve().map()`.
- [x] `.reduce` [Bluebird .reduce](http://bluebirdjs.com/docs/api/reduce.html)
- [x] `.filter` [Bluebird .filter](http://bluebirdjs.com/docs/api/filter.html)
- [x] `.each` [Bluebird .each](http://bluebirdjs.com/docs/api/each.html)
- [x] `.delay` [Bluebird .delay](http://bluebirdjs.com/docs/api/delay.html)
- [x] `Promise.delay` [Bluebird Promise.delay](http://bluebirdjs.com/docs/api/promise.delay.html)
- [x] `.asCallback` [Bluebird .asCallback](http://bluebirdjs.com/docs/api/ascallback.html)
- [ ] `.reflect` [Bluebird .reflect](http://bluebirdjs.com/docs/api/reflect.html)
- [ ] `Promise.promisify` [Bluebird Promise.promisify](http://bluebirdjs.com/docs/api/promise.promisify.html)
- [ ] `Promise.method` [Bluebird Promise.method](http://bluebirdjs.com/docs/api/promise.method.html)

Fix #1027

### CODE REVIEW

**Comment by manast** [comment]
Great work so far.
The other functionality that Bluebird provides and is not available yet in native promises is finally. But I have a custom implementation in queue.js, maybe it can be refactored and used wherever it is needed.

**Comment by pc-jedi** [comment]
I replaced nearly all usages of Bluebird sugar with an own implementation.
They are not perfect, but they get the tests green.
I could not replace `Bluebird.promisify` and `Bluebird.method` yet.

**Comment by btd** [comment]
It is terrible idea to extend Promise.prototype with things out of standard. If you need delay use `p-delay`, if you need promisify use `pify` or `util-promisify`, i think for all or almost all there are utils in npm.
Do you understand that with this PR global promise will be polluted with this methods?

**Comment by pc-jedi** [comment]
@btd Thanks for your feedback :-)
It was just a first start to remove all references to Bluebird and still have all tests green. In the next step I'll get rid of the extended `Promise.protoype`.
If you have some time, we could work together on this PR.

**Comment by manast** [comment]
@btd I guess overwriting the promise prototype is not the most beautiful way to solve this problem, however for things like ```.finally``` I think it is a good compromise, we just need to check that finally is not already there in case the implementation "finally" arrives to node :).

**Comment by btd** [comment]
@manast yes, `.finally` is ok just check missing. I am talking only about non standard things.

**Comment by pc-jedi** [comment]
Closing in favor of #1156

**Pull request closed without merging**
