### PR TITLE
Retry jobs

### PR DESCRIPTION
**Pull request by albertjan**
Adds the ability to retry a job has something to do with #8. I know about #47. This is a much simpler it just adds a function to retry a job. Because it's harder to retry a job when using oxen due to the message.

### CODE REVIEW

**Comment by albertjan** [comment]
@manast the test I added in this PR has disappeared in your last merge :smile:. Do you want me to open another pr?

**Comment by manast** [comment]
oh sure. I don't understand how I managed to merge it away :)

**Comment by manast** [comment]
Btw, I am working on delay functionality which will make the retry functionality better.

**Comment by albertjan** [comment]
Allright cool!

**Pull request merged**
