### PR TITLE
Fix job log pagination

### PR DESCRIPTION
**Pull request by tjhiggins**
https://github.com/OptimalBits/bull/issues/2031

### CODE REVIEW

**Comment by tjhiggins** [comment]
Updated to include asc flag to maintain old behavior, but blocked on:
https://github.com/OptimalBits/bull/issues/2031#issuecomment-841917858

**Comment by manast** [comment]
Please check my comment here: https://github.com/taskforcesh/bullmq/pull/538#issuecomment-842097788

**Comment by tjhiggins** [comment]
@manast updated based on your comment: https://github.com/taskforcesh/bullmq/pull/538#issuecomment-842097788

**Pull request merged**
