### PR TITLE
store handler return value in redis

### PR DESCRIPTION
**Pull request by albertjan**
This makes it possible to return something from the handler. Thus giving the job poster the ability to wait for a job to complete and get the return value. 

Sister PR on oxen: https://github.com/fsprojects/oxen/pull/38

### CODE REVIEW

**Comment by albertjan** [comment]
@manast I've rebased this :smile:

**Comment by manast** [comment]
great stuff by the way ;)

**Comment by albertjan** [comment]
Thanks. :smile: I will update the pr tomorrow.

**Comment by TylerBrock** [comment]
What can I do to help get this merged? @albertjan can you restart the tests to make sure the failure wasn't just a fluke?

**Comment by rossholdway** [comment]
It would be great to get this merged!

**Comment by manast** [comment]
@albertjan should I merge this?

**Comment by albertjan** [comment]
I'll rebase first. Then if you think its good I think it could go in.

**Comment by TylerBrock** [comment]
@albertjan any updates on the rebase?

**Comment by TylerBrock** [comment]
I've tried to fix the linter errors that the tests have but I can't seem to reproduce on my machine.

**Comment by albertjan** [comment]
I'll try just started a new job :)

**Pull request closed without merging**
