### PR TITLE
fix: whenCurrentJobsFinished should wait for all jobs

### PR DESCRIPTION
**Pull request by gabegorelick**
We're currently only waiting for the first job to finish, not all active jobs.

See https://github.com/OptimalBits/bull/pull/1542/files#r356810178

Fixes https://github.com/OptimalBits/bull/issues/1616

### CODE REVIEW

**Comment by gabegorelick** [comment]
Managed to add a test.

**Comment by holm** [comment]
Would be good to have this merged and released

**Comment by gabegorelick** [comment]
@manast it would be good to get this released. Users keep reporting this bug.

**Comment by manast** [comment]
Looks great. I had missed this PR completely.

**Pull request merged**
