### PR TITLE
Store handler return value

### PR DESCRIPTION
**Pull request by albertjan**
Follow up to #178.

Because I don't have access to the other repo anymore.

### CODE REVIEW

**Comment by albertjan** [comment]
`_saveAttempt` is never called with a stacktrace. @evanhuang8 can that be cleaned up?

**Comment by evanhuang8** [comment]
Yeah now that I look at it it's actually wrong, must be a refactor error. `_saveAttempt` should not expect an argument, and the checking should check `this.stacktrace` instead of `stacktrace`

**Comment by albertjan** [comment]
@evanhuang8 I updated it :smile:

**Comment by evanhuang8** [comment]
@albertjan thank you, that was some shitty code I wrote lol

**Comment by albertjan** [comment]
@evanhuang8 you are forgiven :smile: you did a lot of good work for bull lately.

**Comment by evanhuang8** [comment]
@manast it will be nice to have an updated version on `npm` soon, since the stacktrace thing is quite useful

**Comment by TylerBrock** [comment]
yeah, absolutely, would it be too much to ask for you cut a release as well

**Comment by manast** [comment]
New release 0.7.0

**Comment by kimmobrunfeldt** [comment]
Hi guys, if I understood correctly. This PR could help me with [my issue](https://github.com/OptimalBits/bull/issues/214). Could you shortly explain how would I use this new feature to get the return value of a job?

**Pull request merged**
