### PR TITLE
Remove unused module bull-redlock

### PR DESCRIPTION
**Pull request by bradvogel**

### CODE REVIEW

**Comment by bradvogel** [comment]
Note it's into v3.0.0 branch. Are you keeping that in sync with master?

**Comment by manast** [comment]
I think I made a commit or two directly to the 3.0.0 branch by mistake.

**Comment by bradvogel** [comment]
@manast Have you seen Github's Protected Branch features? I use it to prevent accidental pushes to critical branches (eg master). You could use it on v3.0.0 now that we're getting close to merging into master and don't want anything to accidentally sneak in ;)
image

**Comment by manast** [comment]
thats a really cool feature. I activated it right away :)

**Pull request merged**
