### PR TITLE
Remove bluebird

### PR DESCRIPTION
**Pull request by btd**
It does not change Promise.prototype if not need

### CODE REVIEW

**Comment by pc-jedi** [comment]
@btd Nice work. I think I can then close my PR #1153 in favor of this one, since you're already done.

**Comment by manast** [comment]
> It is a bit not clear what you are using yarn or npm, because i see both `yarn.lock` and `package-lock.json`. Also it should be possible to upgrade `ioredis` without issues.
Ok, I just learned that you can use package.lock.json in yarn https://yarnpkg.com/blog/2018/06/04/yarn-import-package-lock/
so no need to keep yarn.lock, at least for the users of the module.

**Comment by btd** [comment]
@manast i noticed your minimum supported node version is 6 (which is currently in maintaince mode). Currentl LTS versions is 8 and 10. But even with 6 supported, it is possible to modernize code base of bull (arrow functions, const/let, destructuring etc). This will greatly improve readability.
With minumum node version 8 it would be possible to use async/await.

**Comment by pc-jedi** [comment]
@btd I agree. Maybe we should create an issue with a task list of what could be modernized.

**Comment by manast** [comment]
@btd I have already started a new codebase in typescript. Bull 4.0 will be typescript only and use some redis 5.0 features as streams for events, etc.

**Comment by btd** [comment]
@manast does this mean that you will not merge anything new to existing code base?

**Comment by manast** [comment]
> @manast does this mean that you will not merge anything new to existing code base?

Of course I will. Bull 4.0 is long way to go anyway, and I will continue making fixes on the 3.x branch.

**Comment by btd** [comment]
Ahh, ok. Thank you.

**Comment by btd** [comment]
@manast what about suggesting about modernizing a bit existing code base (arrow functions, let/const etc)?

**Comment by manast** [comment]
@btd would require babel to keep backwards compatibility with node. Thats why I think it is better to focus the effort on rewriting to typescript, a non-backwards compatible codebase that do not need to inherit many of the ugly hacks we made on the old one.

**Comment by btd** [comment]
No it should not be required to use babel. See node.green. it shows that 6.x supports huge set of es6.

**Comment by manast** [comment]
I am most interested in async/await, which would make most of the codebase much cleaner.

**Comment by pc-jedi** [comment]
@manast Will we get a new bull release which includes this PR?

**Comment by manast** [comment]
@pc-jedi I can release soon, but this is just an internal improvement as far as I understand.

**Comment by zefexdeveloper** [comment]
@manast I'm just getting this error when using Bull, I hope this get merged soon.

**Pull request merged**
