### PR TITLE
Try to be smart about the handler

### PR DESCRIPTION
**Pull request by albertjan**
This tries to resolve the easy to make mistake with specifying a handler with a callback and returning a promise.

It's a bit intricate but it does the job :smile:.

This will make these work:

``` js
queue.process(function(job, done) {
  return Promise.resolve();
});
```

and

```
queue.process(function(job, done) {
  return 5;
});
```

This one will probably create a race condition (for as far as possible in js):

``` js
queue.process(function(job, done) {
   done(5);
   return Promise.resolve(6);
});
```

And this one will outright not work for obvious reasons:

``` js
queue.process(function(job, done) {
  setTimeout(done, 500);
  return 4;
});
```

### CODE REVIEW

**Comment by albertjan** [comment]
@manast have you looked at this? It may help new users.

**Comment by manast** [comment]
It would actually be great to have those examples above as unit tests :)

**Comment by albertjan** [comment]
Yeah I cheated a little on the tests. Will do!

**Comment by albertjan** [comment]
@manast I added tests for this. I'm still not 100% sure this is the right direction. :smile: We might want to educate more and throw an exception when a callback is specified and a promise is returned.

**Comment by manast** [comment]
I think we should deprecate the done callback in version 3 anyway so I will close this PR.

**Pull request closed without merging**
