### PR TITLE
Added methods to find out current job state.

### PR DESCRIPTION
**Pull request by kulbirsaini**
Fixes OptimalBits/bull#162

### CODE REVIEW

**Comment by kulbirsaini** [comment]
I wasn't aware of the `Produce.reduce` usage pattern. I am still learning node. Updated code.

**Comment by kulbirsaini** [comment]
Added lua script to check for items in list.

**Comment by manast** [comment]
Good job!. Now in order to be able to merge this we need to have some unit tests that tests this functionality :)

**Comment by kulbirsaini** [comment]
I am not sure if my current packed schedule will allow me to do that :-( I wonder if someone else familiar with bull test suite could pick it up. I needed this for my internal work urgently so implemented the whole thing.

**Pull request merged**
