### PR TITLE
Adds retry test back in and fixes race conditions

### PR DESCRIPTION
**Pull request by albertjan**
in before hooks. See comments in #72

### CODE REVIEW

**Comment by albertjan** [comment]
Hmm the tests fail but I'm quite sure there's not much wrong with it.

**Comment by manast** [comment]
now that we have delayed functionality, retry should delay the job at every retry attempt, maybe with some time exponential function.

**Comment by albertjan** [comment]
Automatically? Or still triggered? Or maybe with an option?

**Comment by manast** [comment]
I think an option, like retryTime or something similar. or an object for the whole retry functionality:
```javascript
retry: {
 delay: 1000,
 attempts: 5,
}
```

**Comment by manast** [comment]
I think delayed retries is one of the major features missing in bull. If you dont have time I can give this pull request a shot soon.

**Comment by manast** [comment]
forget my previous comment, this is about the test :).

**Pull request closed without merging**
