### PR TITLE
feat: add support for removeOn based on time

### LINKED ISSUE #2265: [Feature] removeOnComplete/Failed based on time
It is often the case that you want to keep completed jobs but just up until a given date instead of a fixed number of them.  Since the completed/finished jobs are currently stored in a zset sorted by timestamp, removing older jobs is quite straightforward.

We would possibly also want to be able to mix both total max with "up to a date", so that we can get both behaviours at the same time if wanted

### PR DESCRIPTION
**Pull request by manast**
Fixes #2265 and #854

### CODE REVIEW

**Comment by jasperkennis** [comment]
Hi @manast , I'm super excited for this update! One question, does @types/bull also require to be updated? It currently doesn't define the new option yet, see [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/911cf7b01956b6555c39ac2cb8b6eee168d3274d/types/bull/index.d.ts#L425).

**Comment by manast** [comment]
I do not maintain the typings sorry...

**Comment by jasperkennis** [comment]
I understand, as a workaround `// @ts-ignore` can be used. I guess `@types/bull` will update eventually. At any rate, super thanks for this update.

**Pull request merged**
