### PR TITLE
add getStalledJobs function

### PR DESCRIPTION
**Pull request by NassiHarel**
In some use cases, in the producer side we want to manually call getStalled and look for stalled jobs, 
if we found some, we want to create a new process with a new job.

### CODE REVIEW

**Comment by NassiHarel** [comment]
Working on it....

**Comment by manast** [comment]
The reason this PR has low chances to get merged is that it is quite a lot of code for a feature that is very niched, sorry for that.

**Comment by NassiHarel** [comment]
Thank you.
Anyway, we use a fork and it's work just fine.

**Comment by maty21** [comment]
hi, can you please merge this PR. we really need this feature in the company that I'm working for, so right now we using this fork   

Thanks

**Comment by manast** [comment]
@maty21 for this to be merged we need that ```lib/commands/getStalledJobs-7.lua```  gets reworked by removing all code that is copied from updateStalledJobs and just leave the code necessary to return the stalled jobs. Other than that the rest of the PR is good enough.

**Comment by NassiHarel** [comment]
@manast 
This PR is old (Dec 24, 2018) and it is also on my private account (https://github.com/NassiHarel/bull).
Since that PR you moved to ES6.
I created a new pull request on the organization account. https://github.com/OptimalBits/bull/pull/1428.

Please take a look.
Thanks.

**Pull request closed without merging**
